# Site settings
title: 於卓慧的宅基地
email: agassi21@gmail.com
description: "但愿每次回忆都不觉愧疚！"
baseurl: ""
url: "http://blog.yuzhuohui.info"
twitter_username: agassi_yzh
github_username: agassiyzh

limit_posts: 5
# Build settings
markdown: kramdown
kramdown:
  input: GFM

permalink: /:year/:month/:day/:title/index.html

timezone: Asia/Shanghai
