baseURL = "http://localhost:1313/"
languageCode = "zn-cn"
defaultContentLanguage = "zn-cn"
title = "小於的宅基地"                         # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true
enableRobotsTXT=true

[author]                               # essential                     # 必需
  name = "小於"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "但愿每次回忆都不觉愧疚"                                       # site's subTitle  # 网站二级标题
  footerSlogan = "人生没有白走的路，每一步都算数"                                   # site's footer slogan  # 网站页脚标语
  keywords = ["技术","园艺","Iot", "生活", "感悟", "育儿"]                                  # site's keywords  # 网站关键字
  description = "小於的个人Blog"                        # site's description  # 网站描述
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
# [params.valine]
#   enable = false
#   appId = ""
#   appKey = ""
#   placeholder = " "
#   visitor = true

# Your socail's url
[social]
  github = "https://github.com/agassiyzh"
  twitter = "https://twitter.com/agassi_yzh"
#  facebook = " "
#  weibo = " "
#  instagram = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
